### PR TITLE
Scala3 derives under `-Yexplicit-nulls` compiler flag

### LINKED ISSUE #1786: `derives Decoder` and `derives Codec.AsObject` fail with -Yexplicit-nulls compiler option
Scala version 3.0.0
Circe version 0.14.1

When the `-Yexplicit-nulls` compiler flag is enabled, `Decoder` derivations like the following fail to compile:
```scala
case class Foo(bar: String) derives io.circe.Decoder
```

I get the following as the first error:
```
[error] -- [E007] Type Mismatch Error: /Users/barnardb/some-project/src/main/scala/c.scala:1:45
[error] 1 |case class Foo(bar: String) derives io.circe.Decoder
[error]   |                                             ^
[error]   |                               Found:    Null
[error]   |                               Required: Left[io.circe.DecodingFailure, ?]
[error]   | This location contains code that was inlined from Derivation.scala:77```
```

As one might expect with the derivation for `Decoder` not working, the following `Codec.AsObject` derivation also fails:
```scala
case class Foo(bar: String) derives io.circe.Codec.AsObject
```

## Background

Scala 3 has a [`-Yexplicit-nulls` compiler option that enables explicit nulls](https://dotty.epfl.ch/docs/reference/other-new-features/explicit-nulls.html). When this flag is enabled, `AnyRef` types such a `String` no longer accept `null` as a value, requiring values to be explicitly marked as being in a union with the `Null` type in order to be nullable. E.g. `val s: String = null` fails to typecheck, but `val s: String | Null = null` does. This allows more safety around the use of nulls.

Note that if explicit nulls are not being used then the type `String | Null` is equivalent to `String`, so by using explicit `… | Null` types for the rare Scala types that are actually nullable we can produce code that works regardless of whether the `-Yexplicit-nulls` option is in use or not.

There is an [`unsafeNulls` language feature](https://dotty.epfl.ch/docs/reference/other-new-features/explicit-nulls.html#unsafenulls) that can be enabled in a particular scope by importing `scala.language.unsafeNulls` to suppress most of the effects of `unsafeNulls` in code that needs a bit of an escape hatch.

## Workaround

Here are some workarounds using `unsafeNulls` that can be used by user of `-Yunsafe-nulls` until this issue is addressed in Circe. The workarounds use `Codec.AsObject`, but they also work with the appropriate adjustments for `Decoder`.

The code compiles if we enable the `unsafeNulls` language feature by importing `scala.language.unsafeNulls`:
```scala
import scala.language.unsafeNulls

case class Foo(bar: String) derives io.circe.Codec.AsObject
```

For top-level declarations though, this prevents us from taking advantage of most of the effects of explicit nulls in the entire file.

If we're willing to repeat code for every type that derives the typeclass, we can move the import to the companion object and reduce the `unsafeNulls` scope to the companion object:
```scala
case class Foo(bar: String) derives io.circe.Codec.AsObject

object Foo {
  import scala.language.unsafeNulls
}
```

But in that case we may as well stop using `derives`, and declare the given typeclass instances manually, limiting the `unsafeNulls` scope to their definitions:
```scala
case class Foo(bar: String)

given io.circe.Codec.AsObject[Foo] = {
  import scala.language.unsafeNulls
  io.circe.Codec.AsObject.derived
}
```

Alternatively, we can define an extension to the trait, and have its derivation use `unsafeNulls`. This is what I'm currently doing in my codebase, because it lets me keep the `derives` style, most of the workaround lives in one place, and it should be easy to remove the shim later with a trivial find-and-replace:
```scala
/** Shim until `dervives Codec.AsObject` works with explicit nulls */
trait CodecAsObject[A] extends io.circe.Codec.AsObject[A]

object CodecAsObject {
  inline def derived[A: scala.deriving.Mirror.Of]: CodecAsObject[A] = {
    new CodecAsObject[A] {
      val derived = {
        import scala.language.unsafeNulls
        io.circe.Codec.AsObject.derived[A]
      }
      def encodeObject(a: A): io.circe.JsonObject = derived.encodeObject(a)
      def apply(c: io.circe.HCursor): io.circe.Decoder.Result[A] = derived.apply(c)
    }
  }
}

case class Foo(bar: String) derives CodecAsObject
```

### PR DESCRIPTION
**Pull request by lqhuang**
Fixes #1786. Projects added `-Yexplicit-nulls` flag cannot compile successfully with Circe.

Previous PR #1788 seems staled, this PR takes same changes but has rebased to the latest head of current master.

The left one problem is I'm not sure whether it's correct and enough to test different compiler flags with or without `-Yexplicit-nulls` (see changes in `build.sbt` and `modules/tests/shared/src/test/scala-3/io/circe/DerivesSuite.scala`).

Your help and feedback are really appreciated.

Thanks!

extra info (without ScalaJS):

```
> sbt +test
[info] Passed: Total 1292, Failed 0, Errors 0, Passed 1292

> sbt +testsNative/test
[info] Passed: Total 1292, Failed 0, Errors 0, Passed 1292
```

### CODE REVIEW

**Comment by lqhuang** [comment]
@rossabaker Could you help to give a review here. Thx :)

**Comment by rossabaker** [comment]
I am not yet a Scala 3 user other than compiling several libraries for it, but this seems reasonable to me, and addresses my concern with the prior PR.

**Comment by lqhuang** [comment]
It's strange that I passed all tests with similar conditions (temurin@8, rootJVM).

My local dev environment

```
$ uname -a
Darwin iMac.local 22.3.0 Darwin Kernel Version 22.3.0

$ scala -version
Scala code runner version 3.2.1 -- Copyright 2002-2022, LAMP/EPFL
```

Tested for two JVM versions

```
$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)
```

How could we rerun actions?

**Comment by rossabaker** [comment]
I can rerun it, but compiler errors are usually not flakes.  In case it suddenly passes, here's the 3.2.1, temurin@8, rootJVM failure:

```
 [error] -- Error: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala-3/io/circe/DerivesSuite.scala:134:56 
[error] 134 |  checkAll("Codec[Seq[Foo]]", CodecTests[Seq[Foo]].codec)
[error]     |                                                        ^
[error]     |Ambiguous given instances: both method eqSeq in trait MissingInstances and method catsKernelStdEqForSeq in trait SeqInstances2 match type cats.kernel.Eq[Seq[io.circe.DerivesSuite.Foo]] of parameter eqA of method codec in trait CodecTests
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JsonNumberSuite.scala:184:21 
[warn] 184 |      runCompareTest(JsonFloat, f, JsonLong, l)
[warn]     |                     ^^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.JsonFloat.apply` explicitly.
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JsonNumberSuite.scala:184:35 
[warn] 184 |      runCompareTest(JsonFloat, f, JsonLong, l)
[warn]     |                                   ^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.JsonLong.apply` explicitly.
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JsonNumberSuite.scala:190:21 
[warn] 190 |      runCompareTest(JsonFloat, f, JsonDouble, d)
[warn]     |                     ^^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.JsonFloat.apply` explicitly.
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JsonNumberSuite.scala:190:35 
[warn] 190 |      runCompareTest(JsonFloat, f, JsonDouble, d)
[warn]     |                                   ^^^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.JsonDouble.apply` explicitly.
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JsonNumberSuite.scala:196:21 
[warn] 196 |      runCompareTest(JsonFloat, f1, JsonFloat, f2)
[warn]     |                     ^^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.JsonFloat.apply` explicitly.
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/JsonNumberSuite.scala:196:36 
[warn] 196 |      runCompareTest(JsonFloat, f1, JsonFloat, f2)
[warn]     |                                    ^^^^^^^^^
[warn]     |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.JsonFloat.apply` explicitly.
[warn] -- Warning: /home/runner/work/circe/circe/modules/tests/shared/src/test/scala/io/circe/ShowErrorSuite.scala:39:70 
[warn] 39 |  val downFields: Gen[List[CursorOp]] = Gen.listOf(Gen.identifier.map(DownField))
[warn]    |                                                                      ^^^^^^^^^
[warn]    |The method `apply` is inserted. The auto insertion will be deprecated, please write `io.circe.CursorOp.DownField.apply` explicitly.
[warn] 7 warnings found
[error] one error found
[error] (testsJVM / Test / compileIncremental) Compilation failed
```

**Comment by lqhuang** [comment]
Thanks! But seems more failures 😢, I will try to test them on Linux or exact Ubuntu distribution.

**Comment by rossabaker** [comment]
I suspect the problem here is that the build is failing on a [merge ref](https://github.com/circe/circe/actions/runs/4054143028/jobs/6999230943#step:2:677).  That commit isn't the HEAD of your PR branch, but a merge commit that would result from merging this PR into main.  While your branch is healthy, and main is healthy, the merge that would result is not.  GitHub tests this merge commit to guard against these "semantic merge conflicts".

It's complaining about an amibiguous implicit instance.  I didn't dig too deep, but my guess is that Cats added it since the original author started this PR, and now it's conflicting with one Circe had in `MissingInstances`.  You probably can't remove that Circe instance due to binary compatibility, but if you remove its `implicit` keyword (and, ideally, deprecate it), I bet everything will work.  

If you merge the latest main into your branch, I expect you'll see this error locally and be able to fix it.

File: modules/tests/shared/src/main/scala-3/io/circe/tests/CirceMunitSuite.scala [hunk 1]
```diff
@@ -0,0 +1,29 @@
+package io.circe.tests
+
+import io.circe.testing.{ ArbitraryInstances, EqInstances }
+import munit.DisciplineSuite
+
+/**
+ * An opinionated stack of traits to improve consistency and reduce boilerplate in circe tests.
+ */
+trait CirceMunitSuite extends DisciplineSuite with ArbitraryInstances with EqInstances with MissingInstances {
```
Comment (zarthross) [inline modules/tests/shared/src/main/scala-3/io/circe/tests/CirceMunitSuite.scala]: Rather than duplicating `CirceMunitSuite` can you make a `PlatformSpecificInstances` trait for scala-2 and scala-3 and have `CirceMunitSuite` extend it?

**Review by zarthross — CHANGES_REQUESTED** [review]

File: modules/tests/shared/src/main/scala-3/io/circe/tests/CirceMunitSuite.scala (hunk 1 above)
Comment (lqhuang) [reply modules/tests/shared/src/main/scala-3/io/circe/tests/CirceMunitSuite.scala]: Ok, I will try to implement this as I could

Comment (lqhuang) [reply modules/tests/shared/src/main/scala-3/io/circe/tests/CirceMunitSuite.scala]: Fixed. I found it's probably not necessary to add an extra trait.

**Comment by lqhuang** [comment]
@zarthross @rossabaker Could you review again? I have fixed problems and addressed change requests.

Thank you for your helps!

File: modules/tests/shared/src/test/scala-3/io/circe/DerivesSuite.scala [hunk 2]
```diff
@@ -137,4 +135,14 @@ class DerivesSuite extends CirceMunitSuite {
...
+
+  property("Derives under `-Yexplicit-nulls` should work") {
+    val settings = staging.Compiler.Settings.make(compilerArgs = List("-Yexplicit-nulls"))
+    val explicitNullsCompiler = staging.Compiler.make(getClass.getClassLoader)(settings)
+    staging.run('{
+      val encoder = Encoder.AsObject.derived[Box[Wub]];
+      val decoder = Decoder.derived[Box[Wub]];
+      val codec = Codec.AsObject.derived[Box[Wub]];
+    })(using explicitNullsCompiler)
+  }
```
Comment (zarthross) [inline modules/tests/shared/src/test/scala-3/io/circe/DerivesSuite.scala]: Can you move this test to a jvm specific test suite (modules/tests/jvm/...`)?   I don't think this will work on ScalaJS or ScalaNative based on the errors I'm seeing in CI.

**Comment by zarthross** [comment]
We need to get this branch updated and conflicts resolved, there was a big PR that refactored Derivation that just went through.

**Comment by lqhuang** [comment]
@zarthross Ok. Thank you for the reminder. I would rebase it later (probably weekend) and reorg the tests (I have passed native tests, is trying to reduce boilerplate codes for now).

File: modules/tests/shared/src/test/scala-3/io/circe/DerivesSuite.scala (hunk 2 above)
Comment (lqhuang) [reply modules/tests/shared/src/test/scala-3/io/circe/DerivesSuite.scala]: OK, Done

**Comment by lqhuang** [comment]
@zarthross It's ready for review. And actually, after my tests, using the latest release 0.14.4, Circe can be successfully compiled by **user's library** with `-Yexplicit-nulls` flag. Hence, this PR doesn't modify any logical code, but only add a unit-test to make sure Circe could be normally compiled in third lib/app. Yeah, it just tests compiling.

Honestly, it's also fine for me to reject PR. Both `-Yexplicit-nulls` and `staging` are not very stable features in Scala 3 for now. Worry about causing extra unit-test errors in the future.

**Review by zarthross — CHANGES_REQUESTED** [review]
I'm really not sure what these tests are actually testing right now?  I tried adding this test and it still passes.

```
  test("Java boxed class would not compile without `.nn` postfix with `-Yexplicit-nulls`") {
    def code(using Quotes) = '{
      given Encoder[Instant] = Encoder.encodeString.contramap[Instant](t =>
        ISO_OFFSET_DATE_TIME
          .format(
            t.truncatedTo(MILLIS).atOffset(ZoneOffset.UTC)
          )
      )
      given Codec[Event] = Codec.AsObject.derived[Event]
    }

    staging.run(code)
  }
```

I realize the assertion is not correct, but i wanted to see this fail before i wrote the assertion, and when the test passed it told me the other tests passing could be a false positive.

**Comment by lqhuang** [comment]
@zarthross Thanks for your reply. It comes from a real case. Yeah, as I said:

> And actually, after my tests, using the latest release 0.14.4, Circe can be successfully compiled by user's library with -Yexplicit-nulls flag.

Here is my minimal reproduction:

```scala
import java.time.Instant
import java.time.format.DateTimeFormatter.ISO_OFFSET_DATE_TIME
import java.time.temporal.ChronoUnit.MILLIS

import io.circe.{Codec, Encoder, Json}
import io.circe.syntax.*
import io.circe.parser.{decode, parse}

given Encoder[Instant] =
  Encoder.encodeString.contramap[Instant](t =>
    ISO_OFFSET_DATE_TIME.nn.format(t.truncatedTo(MILLIS).nn).nn
  )

case class InEvent(id: Int, name: String, eventTime: Instant)
    derives Codec.AsObject

@main def hello: Unit =
  val rawJson: String = """
    {
      "id": 13,
      "name": "test-event",
      "eventTime": "2023-01-05T08:04:55.697Z"
    }
    """
  val inEvent = parse(rawJson)
    .flatMap(_.as[InEvent])
    .getOrElse(InEvent(0, "error", Instant.now().nn))
  println(s"${inEvent}")
  println(msg)

def msg = "I was compiled by Scala 3 with Circe :)"
```

And `build.sbt`:

```
val scala3Version = "3.2.2"
val circeVersion = "0.14.3"

scalacOptions ++= Seq("-explain", "-Yexplicit-nulls")

lazy val root = project
  .in(file("."))
  .settings(
    name := "circe-nn-boxed",
    version := "0.1.0-SNAPSHOT",
    scalaVersion := scala3Version,
    libraryDependencies ++= Seq(
      "io.circe" %% "circe-core" % circeVersion,
      "io.circe" %% "circe-parser" % circeVersion,
      "org.scalameta" %% "munit" % "0.7.29" % Test
    )
  )
```

Above sample codes will successfully be compiled and run with `circeVersion = "0.14.4"` but failed with `circeVersion = "0.14.3"` (check following error msgs):

```
[error] -- [E007] Type Mismatch Error: /Users/lqhuang/Git/circe-nn-boxed/src/main/scala/Main.scala:15:18
[error]  15 |    derives Codec.AsObject
[error]     |                  ^
[error]     |                  Found:    Null
[error]     |                  Required: Left[io.circe.DecodingFailure, ?]
[error]     |---------------------------------------------------------------------------
[error]     |Inline stack trace
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |This location contains code that was inlined from Derivation.scala:162
[error]      ---------------------------------------------------------------------------
[error]     |---------------------------------------------------------------------------
[error]     | Explanation (enabled by `-explain`)
[error]     |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]     |
[error]     | Tree: null
[error]     | I tried to show that
[error]     |   Null
[error]     | conforms to
[error]     |   Left[io.circe.DecodingFailure, ?]
[error]     | but the comparison trace ended with `false`:
[error]     |
[error]     |   ==> Null  <:  Left[io.circe.DecodingFailure, ?]
[error]     |   <== Null  <:  Left[io.circe.DecodingFailure, ?] = false
[error]     |
[error]     | The tests were made under the empty constraint
[error]      ---------------------------------------------------------------------------
[error] Explanation
[error] ===========
[error]
[error] Tree: null
[error] I tried to show that
[error]   Null
[error] conforms to
[error]   Left[io.circe.DecodingFailure, ?]
[error] but the comparison trace ended with `false`:
[error]
[error]   ==> Null  <:  Left[io.circe.DecodingFailure, ?]
[error]   <== Null  <:  Left[io.circe.DecodingFailure, ?] = false
[error]
[error] The tests were made under the empty constraint
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Mar 16, 2023, 4:51:28 PM
```

You could download this to setup project [minimal-reproductions.zip](https://github.com/circe/circe/files/10988697/minimal-reproductions.zip).

> Hence, this PR doesn't modify any logical code, but only add a unit-test to make sure Circe could be normally compiled in third lib/app. Yeah, it just tests compiling.

Honestly, **I have tried rebase to history to find which commits fix this problem**, but I don't locate it yet. I will be appreciated if someone could teach me how to use `git bisect` in depth.

**Comment by lqhuang** [comment]
There is a type mismatching error if we do not use `.nn` to cast Java boxed object. It's an interoperability issue between Java and Scala when enabling `-Yexplicit-nulls` [Scala 3 Docs](https://docs.scala-lang.org/scala3/reference/experimental/explicit-nulls.html)

**Comment by zarthross** [comment]
@lqhuang I completely understand what you are trying to do, you are trying to make a test to prevent the regression of support for `-Yexplicit-nulls` and I appreciate that, but your test does not verify that.  If you take your test `Java boxed class would require '.nn' postfix with '-Yexplicit-nulls'` and remove the `.nn` annotations, the tests still passes when it clearly shouldn't based on the test name.   I'm just NOT convinced that these test will prevent a regression.

I think something is wrong with your use of `staging` such that the error you are trying to test for, just doesn't surface.

**Comment by lqhuang** [comment]
@zarthross You're right! It's my faults. And I did some experiments and found both test cases are not actually compiled then run. Even the simplest demo not works ether.

That's probably why I didn't find which commit fix issue.

**Comment by lqhuang** [comment]
Here is my experiment. I create a Scala 3 project and using staging API to write codes directly. And I upload these codes to a repo: <https://github.com/lqhuang/minimal-reproducible-issues/tree/staging-with-case-class-and-circe> `staging-with-case-class-and-circe` branch or download it from attachments [staging-with-case-class-and-circe-master.zip](https://github.com/circe/circe/files/11028738/staging-with-case-class-and-circe-master.zip).

All 3 cases cannot normally run. There are some limits in current staging API.

## Case 1

```scala
import io.circe.{Codec, Encoder, Json, Decoder}
import io.circe.syntax.*
import io.circe.parser.{decode, parse}

import scala.quoted.staging
import scala.quoted.{Quotes, Type}

@main def Case1: Unit = {
  val settings =
    staging.Compiler.Settings.make(compilerArgs = List("-Yexplicit-nulls"))
  given explicitNullsCompiler: staging.Compiler =
    staging.Compiler.make(getClass.getClassLoader)(settings)

  def code(using Quotes) = '{
    case class Foo(val i: Int, val s: String)

    given Codec[Foo] = Codec.AsObject.derived[Foo]
    given Decoder[Foo] = Decoder.derived[Foo]
    given Encoder[Foo] = Encoder.AsObject.derived[Foo]

    println(
      "Case class definitions are not allowed in inline methods or quoted code. Use a normal class instead."
    )

  }

  staging.run(code)
}
```

Compiler tells me that `case class` cannot be defined in quoted scope.

```
Case class definitions are not allowed in inline methods or quoted code. Use a normal class instead.
```

### Case 2

I moved the `case` to outside scope and add missing `Type[T]`, but failed again

```scala
import io.circe.{Codec, Encoder, Json, Decoder}
import io.circe.syntax.*
import io.circe.parser.{decode, parse}

import scala.quoted.staging
import scala.quoted.{Quotes, Type}

@main def Case2: Unit = {
  val settings =
    staging.Compiler.Settings.make(compilerArgs = List("-Yexplicit-nulls"))
  given explicitNullsCompiler: staging.Compiler =
    staging.Compiler.make(getClass.getClassLoader)(settings)

  case class Foo(val i: Int, val s: String) derives Codec.AsObject

  def expr(using Quotes, Type[Foo]) = '{
    given Codec[Foo] = Codec.AsObject.derived[Foo]
    given Decoder[Foo] = Decoder.derived[Foo]
    given Encoder[Foo] = Encoder.AsObject.derived[Foo]

    println(
      """access to object Foo from wrong staging level:
        |  - the definition is at level 0,
        |  - but the access is at level 1.
        """.stripMargin
    )
  }

  staging.run(expr)
}
```

Compiler error:

```
access to object Foo from wrong staging level:
  - the definition is at level 0,
  - but the access is at level 1.
```

Seems because the `Foo` is defined in the top level scope (level 0), but derives declaration is defined in the Quotes scope (level 1). This is not allowed in stage API, too.

## Case 3

In case 3, just define original `class` and write companion object with custom codec manually (`derive` feature requires case class). Codes compiled successfully, but failed in runtime. I'm not very sure whether it's caused by importing circe packages.

```scala
import scala.quoted.{Quotes, staging, Type}

@main def Case3: Unit = {
  val settings =
    staging.Compiler.Settings.make(compilerArgs = List("-Yexplicit-nulls"))
  given explicitNullsCompiler: staging.Compiler =
    staging.Compiler.make(getClass.getClassLoader)(settings)

  def code(using Quotes) = '{
    import io.circe.{Codec, Encoder, Json, Decoder}
    import io.circe.syntax.*
    import io.circe.parser.{decode, parse}
    import io.circe.JsonObject

    class Foo(val i: Int, val s: String) {
      override def toString(): String = s"Foo($i, $s)"
    }

    object Foo {
      def apply(i: Int, s: String): Foo = new Foo(i, s)

      given Codec.AsObject[Foo] = {
        Codec.AsObject.from(
          Decoder.instance(c =>
            for {
              i <- c.downField("i").as[Int]
              s <- c.downField("s").as[String]
            } yield Foo(i, s)
          ),
          Encoder.AsObject.instance[Foo](x =>
            JsonObject(
              "i" -> Json.fromInt(x.i),
              "s" -> Json.fromString(x.s)
            )
          )
        )
      }
    }

    parse("{'i': 1, 's': 'string'}").flatMap(_.as[Foo]) match {
      case Left(error) => println(error)
      case Right(foo)  => println(foo)
    }
  }

  staging.run(code)
}
```

Error info:

```
[error] class dotty.tools.dotc.reporting.Diagnostic$Error at src/main/scala/Case3.scala:<1098..1129>: undefined: io.circe.parser.package.parse # -1: TermRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class circe)),object parser),package),parse) at quotedFrontend
[error] 	at dotty.tools.dotc.report$.error(report.scala:78)
[error] 	at dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:36)
[error] 	at dotty.tools.dotc.typer.ErrorReporting$.errorType(ErrorReporting.scala:41)
[error] 	at dotty.tools.dotc.typer.TypeAssigner.assignType(TypeAssigner.scala:306)
[error] 	at dotty.tools.dotc.typer.TypeAssigner.assignType$(TypeAssigner.scala:16)
[error] 	at dotty.tools.dotc.typer.Typer.assignType(Typer.scala:121)
[error] 	at dotty.tools.dotc.ast.tpd$.Apply(tpd.scala:49)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1236)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1297)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1238)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1233)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1282)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler.dotty$tools$dotc$core$tasty$TreeUnpickler$TreeReader$$_$_$$anonfun$26(TreeUnpickler.scala:1249)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readIndexedStats(TreeUnpickler.scala:1095)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readStats(TreeUnpickler.scala:1099)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1249)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readLengthTerm$1(TreeUnpickler.scala:1259)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1394)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler$TreeReader.readTerm(TreeUnpickler.scala:1117)
[error] 	at dotty.tools.dotc.core.tasty.TreeUnpickler.unpickle(TreeUnpickler.scala:113)
[error] 	at dotty.tools.dotc.core.tasty.DottyUnpickler.computeRootTrees(DottyUnpickler.scala:62)
[error] 	at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees(tpd.scala:1280)
[error] 	at dotty.tools.dotc.ast.tpd$TreeProvider.rootTrees$(tpd.scala:1269)
[error] 	at dotty.tools.dotc.core.tasty.DottyUnpickler.rootTrees(DottyUnpickler.scala:44)
[error] 	at dotty.tools.dotc.ast.tpd$TreeProvider.tree(tpd.scala:1284)
[error] 	at dotty.tools.dotc.ast.tpd$TreeProvider.tree$(tpd.scala:1269)
[error] 	at dotty.tools.dotc.core.tasty.DottyUnpickler.tree(DottyUnpickler.scala:44)
[error] 	at dotty.tools.dotc.quoted.PickledQuotes$.unpickle(PickledQuotes.scala:257)
[error] 	at dotty.tools.dotc.quoted.PickledQuotes$.unpickleTerm(PickledQuotes.scala:83)
[error] 	at scala.quoted.runtime.impl.QuotesImpl.unpickleExprV2(QuotesImpl.scala:3044)
[error] 	at Case3$package$.code$1(Case3.scala:10)
[error] 	at Case3$package$.Case3$$anonfun$1(Case3.scala:47)
[error] 	at scala.quoted.staging.QuoteCompiler$QuotedFrontend.runOn$$anonfun$1(QuoteCompiler.scala:83)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:293)
[error] 	at scala.quoted.staging.QuoteCompiler$QuotedFrontend.runOn(QuoteCompiler.scala:98)
[error] 	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:238)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] 	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error] 	at dotty.tools.dotc.Run.runPhases$1(Run.scala:249)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:257)
[error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:266)
[error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:68)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:266)
[error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:196)
[error] 	at scala.quoted.staging.QuoteCompiler$ExprRun.compileExpr(QuoteCompiler.scala:118)
[error] 	at scala.quoted.staging.QuoteDriver.run(QuoteDriver.scala:43)
[error] 	at scala.quoted.staging.Compiler$$anon$1.run(Compiler.scala:38)
[error] 	at scala.quoted.staging.package$.run(staging.scala:19)
[error] 	at Case3$package$.Case3(Case3.scala:47)
[error] 	at Case3.main(Case3.scala:3)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[error] stack trace is suppressed; run last Compile / runMain for the full output
[error] (Compile / runMain) class dotty.tools.dotc.reporting.Diagnostic$Error at src/main/scala/Case3.scala:<1098..1129>: undefined: io.circe.parser.package.parse # -1: TermRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class circe)),object parser),package),parse) at quotedFrontend
[error] Total time: 1 s, completed Mar 21, 2023, 8:33:41 PM
```

**Comment by lqhuang** [comment]
I have no idea about how to solve it. If you have other approaches to test these behaviors, I'm glad to try it and help.

Anyway, @zarthross, really appreciate to your patience! Sorry to waste your time.

I will close the PR now or reopen it until we get something new progress in the future.

Thanks for your time!

**Comment by zarthross** [comment]
No problem!  I'm sorry we weren't able to get a test working.  Thanks for trying!  Maybe we can retry with a future Scala 3 version 😅
