### ISSUE TITLE
Runtime error when using Shapeless > 2.3.3

### ISSUE THREAD

**Issue by soujiro32167** [circe/circe#1743]
I am getting a strange error at runtime, which I could not reproduce:

```
java.lang.NoClassDefFoundError: shapeless/ops/hlist$ZipWithKeys$$anon$158
[info]   at com.byond.infinity.defs$ProgramResponse$anon$lazy$macro$25$1.inst$macro$1$lzycompute(defs.scala:93)
[info]   at com.byond.infinity.defs$ProgramResponse$anon$lazy$macro$25$1.inst$macro$1(defs.scala:93)
[info]   at com.byond.infinity.defs$ProgramResponse$.<clinit>(defs.scala:93)
```

Here is the line:

```scala
case class ProgramResponse(
    id: UUID,
    name: String,
    description: String,
    program: String,
    dependencies: Dependencies,
    created: Instant,
    updated: Instant,
    createdBy: Option[String],
    updatedBy: Option[String]
  )

  object ProgramResponse {
    implicit val decoder: Decoder[ProgramResponse] = deriveDecoder
    implicit val encoder: Encoder[ProgramResponse] = deriveEncoder
  }

final case class Dependencies(value: List[String]) extends AnyVal
object Dependencies {
    implicit val decoder: Decoder[Dependencies] = Decoder[List[String]].map(Dependencies.apply)
    implicit val encoder: Encoder[Dependencies] = Encoder[List[String]].contramap(_.value)

  }
```

This only happens when I upgraded a dependency that used shapeless 2.3.5 (2.3.4 gives the same results).

Scala version: 2.13.5
Circe version: 0.13.0

Please help

**Comment by travisbrown** [comment]
Have you tried Shapeless 2.3.6? It's possible that you're seeing [this issue](https://github.com/milessabin/shapeless/pull/1153). You might also try cleaning and rebuilding the module that contains these definitions after the upgrade.

**Comment by travisbrown** [comment]
If you can post a complete working example showing the issue, I can take a look, but I wasn't able to reproduce it given the code above.

**Comment by armanbilge** [comment]
It looks like this issue may relate to macro derivation, which shapeless only just began guaranteeing binary compatibility for as of 2.3.6.

**Comment by armanbilge** [comment]
Now that my project compiles on shapeless 2.3.7, I am getting a similar exception.

```
Exception in thread "main" java.lang.NoSuchMethodError: 'shapeless.DefaultSymbolicLabelling shapeless.DefaultSymbolicLabelling$.instance(shapeless.HList)'
	at s.o.app.Server$anon$importedDecoder$macro$375$1.inst$macro$1$lzycompute(Server.scala:48)
	at s.o.app.Server$anon$importedDecoder$macro$375$1.inst$macro$1(Server.scala:48)
	at s.o.app.Server$.main(Server.scala:48)
	at s.o.app.Server.main(Server.scala)
```

I'll try and put together a working example.

**Comment by soujiro32167** [comment]
tried with 2.3.7, still same result; and, sadly, I cannot reproduce on Scastie...
N00b question: Is `sbt clean test` enough to do a clean rebuild?
