### ISSUE TITLE
Unexpected Scala 3 compilation error when upgrading from 0.14.10 to 0.14.11

### ISSUE THREAD

**Issue by plokhotnyuk** [circe/circe#2361]
```
[error] dotty.tools.dotc.reporting.UnhandledError: class DecoderNotDeriveSum cannot be accessed as a member of io.circe.derivation.type from object CirceEncodersDecoders.
[error]   private[circe] class DecoderNotDeriveSum can only be accessed from package io.circe in package io.
[error] dotty.tools.dotc.reporting.ThrowingReporter.doReport(ThrowingReporter.scala:14)
[error] dotty.tools.dotc.reporting.Reporter.issueUnconfigured(Reporter.scala:160)
[error] dotty.tools.dotc.reporting.Reporter.go$1(Reporter.scala:191)
[error] dotty.tools.dotc.reporting.Reporter.issueIfNotSuppressed(Reporter.scala:210)
[error] dotty.tools.dotc.reporting.Reporter.report(Reporter.scala:213)
[error] dotty.tools.dotc.reporting.Reporter.flush$$anonfun$1(Reporter.scala:277)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:334)
[error] dotty.tools.dotc.reporting.Reporter.flush(Reporter.scala:277)
[error] dotty.tools.dotc.core.TyperState.commit(TyperState.scala:177)
```
Steps to reproduce:

 1. Run `git clone --depth 1 https://github.com/plokhotnyuk/jsoniter-scala`
 2. Run `cd jsoniter-scala`
 3. Run `sed -i 's/0.14.10/0.14.11/g' build.sbt`
 4. Run `sbt ++3.6.4! jsoniter-scala-benchmarkJVM/test`

**Comment by kaesler** [comment]
I see the same problem.

**Comment by mrdziuban** [comment]
Seems like it was introduced in #2341

**Comment by MartinHH** [comment]
Minimal reproducer:

```scala
//> using dep "io.circe::circe-core::0.14.11"
//> using scala "3.6.4"

import io.circe.*

case class Value(value: String) 

object Codecs:
  given Decoder[Value] = Decoder.derived
  given Encoder[Value] = Encoder.derived
```
