### ISSUE TITLE
java.lang.NoSuchMethodError after upgrading from 0.11 to 0.13

### ISSUE THREAD

**Issue by wangt328** [circe/circe#1446]
Hi - Not sure this is the right place to ask question about circe, but decide to try my luck here. After upgrading my circe from version 0.11 to 0.13, I am seeing this error, 

```
 java.lang.NoSuchMethodError: io.circe.Encoder$.encodeJsonObject()Lio/circe/ObjectEncoder;
```

Any hint how this may be resolved? Thank you very much!
