### ISSUE TITLE
Deriving Decoders and Encoders via semiauto doesn't work on Scala 2.12.5

### ISSUE THREAD

**Issue by bandrzejczak** [circe/circe#867]
The following code compiles under Scala 2.12.4:

```
case class Bla(a: Int, b: String)
implicit val decodeBla: Decoder[Bla] = deriveDecoder[Bla]
implicit val encodeBla: Encoder[Bla] = deriveEncoder[Bla]
```

Under Scala 2.12.5 it cases the following compilation error:
```
[error] Test.scala:17:55: implicit error;
[error] !I decode: DerivedDecoder[Bla]
[error]   implicit val decodeBla: Decoder[Bla] = deriveDecoder[Bla]
[error]                                                       ^
[error] Test.scala:18:55: implicit error;
[error] !I encode: DerivedObjectEncoder[Bla]
[error]   implicit val encodeBla: Encoder[Bla] = deriveEncoder[Bla]
[error]                                                       ^
```

I've tested that for circe 0.9.0 and 0.9.3.

**Comment by travisbrown** [comment]
Can you share more about your setup? It seems to work fine for me:

```scala
Welcome to Scala 2.12.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> import io.circe.{ Decoder, Encoder }, io.circe.generic.semiauto._
import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto._

scala> case class Bla(a: Int, b: String)
defined class Bla

scala> implicit val decodeBla: Decoder[Bla] = deriveDecoder[Bla]
decodeBla: io.circe.Decoder[Bla] = io.circe.generic.decoding.DerivedDecoder$$anon$1@3bee72d4

scala> implicit val encodeBla: Encoder[Bla] = deriveEncoder[Bla]
encodeBla: io.circe.Encoder[Bla] = io.circe.generic.encoding.DerivedObjectEncoder$$anon$1@f85754c
```

**Comment by bandrzejczak** [comment]
Ugh, It must've been something else, sorry for the confusion. For some reason it compiled under 2.12.4 and crashed with circe implicit errors under 2.12.5. Now it's all back to normal on 2.12.5.

**Comment by oschrenk** [comment]
I actually having similar issues.

**Comment by oschrenk** [comment]
The example from the documentation don't work under 2.12.5 but do work with 2.12.4

```build.sbt
lazy val root = (project in file(".")).
  settings(
    inThisBuild(List(
      organization := "com.example",
      scalaVersion := "2.12.4",
      version      := "0.1.0-SNAPSHOT"
    )),
    name := "circe",
    libraryDependencies ++= Seq(
      "io.circe" %% "circe-core" % "0.9.3",
      "io.circe" %% "circe-parser" % "0.9.3",
      "io.circe" %% "circe-generic" % "0.9.3"
    )
  )

```


```Hello.scala
package example

object Hello extends Greeting with App {
  println(greeting)
  import io.circe._, io.circe.generic.auto._, io.circe.parser._, io.circe.syntax._

  sealed trait Foo
  case class Bar(xs: Vector[String]) extends Foo
  case class Qux(i: Int, d: Option[Double]) extends Foo

  val foo: Foo = Qux(13, Some(14.0))

  val json = foo.asJson.noSpaces
  println(json)

  val decodedFoo = decode[Foo](json)
  println(decodedFoo)
}

trait Greeting {
  lazy val greeting: String = "hello"
}
```

with `2.12.5` as `scalaVersion`I get

```
[error] /Users/oliver/Projects/external/circe/src/main/scala/example/Hello.scala:13:18: could not find implicit value for parameter encoder: io.circe.Encoder[example.Hello.Foo]
[error]   val json = foo.asJson.noSpaces
[error]                  ^
[error] /Users/oliver/Projects/external/circe/src/main/scala/example/Hello.scala:16:31: could not find implicit value for evidence parameter of type io.circe.Decoder[example.Hello.Foo]
[error]   val decodedFoo = decode[Foo](json)
[error]                               ^
[error] two errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 4 s, completed 18 Apr 2018, 22:45:38
```

while with `2.12.4` I get

[info] Done packaging.
[info] Running example.Hello
hello
{"Qux":{"i":13,"d":14.0}}
Right(Qux(13,Some(14.0)))
```

**Comment by oschrenk** [comment]
Oh. I think this is https://github.com/scala/scala-dev/issues/480

**Comment by travisbrown** [comment]
@oschrenk Are you on JDK 9 / 10? We're not currently testing those, but I think we'll need to start soon.

**Comment by oschrenk** [comment]
Yes. I think this is https://github.com/scala/scala-dev/issues/480. I was going slightly crazy for a while, thinking I forgot how to Scala and Circe.

**Comment by kyrsideris** [comment]
Firstly, thanks for `circe` @travisbrown !

I have have a similar problem in Scala 2.12.8 on Java 11 with circe 0.11.1.
```sbt
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 11.0.2).
Type in expressions for evaluation. Or try :help.

scala> import io.circe.{ Decoder, Encoder }, io.circe.generic.semiauto._
import io.circe.{Decoder, Encoder}
import io.circe.generic.semiauto._

scala> import com.hotels.road.weighbridge.model.PartitionReplica
import com.hotels.road.weighbridge.model.PartitionReplica

scala> implicit val partitionReplicaDecoder: Decoder[PartitionReplica] = deriveDecoder[PartitionReplica]
<console>:16: error: could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[com.hotels.road.weighbridge.model.PartitionReplica]
       implicit val partitionReplicaDecoder: Decoder[PartitionReplica] = deriveDecoder[PartitionReplica]
                                                                                      ^
```
To reproduce, you will need:
```xml
    <dependency>
      <groupId>com.hotels.road</groupId>
      <artifactId>road-weigh-bridge</artifactId>
      <version>6.0.6</version>
    </dependency>
```
`PartitionReplica` is a Java `lombok.Value` class.

Is this problem related to Java/Lombok or Scala 2.12.8/Java 11?
Thanks!
